//! Which language the Generate code dialog is showing.
//!
//! A closed enum for the same reason [`BodyType`] and [`HttpMethod`] are closed:
//! every branch that maps a target to a label, an editor grammar or an emitter
//! is exhaustive, so adding a target cannot silently miss one.
//!
//! The *code* is generated by [`services::codegen`]; this module only names the
//! choices. It lives in `models` rather than beside the emitters because the
//! dialog enumerates targets and must not reach into the service layer to do it.
//!
//! [`BodyType`]: crate::api_explorer::models::body::BodyType
//! [`HttpMethod`]: crate::api_explorer::models::method::HttpMethod
//! [`services::codegen`]: crate::api_explorer::services::codegen

use crate::i18n::Str;

/// The four languages a request can be turned into.
///
/// Node's `http`/`https` was offered and deliberately not chosen — nothing here
/// is shaped to prevent it, but it is not a target this build has.
#[derive(Clone, Copy, PartialEq, Eq, Debug, Default)]
pub enum CodeTarget {
    #[default]
    Curl,
    JsFetch,
    JsAxios,
    JsXhr,
}

impl CodeTarget {
    pub const ALL: [CodeTarget; 4] = [
        CodeTarget::Curl,
        CodeTarget::JsFetch,
        CodeTarget::JsAxios,
        CodeTarget::JsXhr,
    ];

    /// The tab label. Every one is the name of a tool or of a browser API, so
    /// each reads the same in both languages — see the `term()` declarations in
    /// `i18n`'s tests.
    pub fn label(self) -> Str {
        match self {
            CodeTarget::Curl => Str::CodeTargetCurl,
            CodeTarget::JsFetch => Str::CodeTargetFetch,
            CodeTarget::JsAxios => Str::CodeTargetAxios,
            CodeTarget::JsXhr => Str::CodeTargetXhr,
        }
    }

    /// The grammar the snippet is shown in.
    ///
    /// `javascript` is compiled into this build (`Cargo.toml`'s
    /// `syntax-highlighting` feature, added for the Scripts tab). A shell
    /// grammar is not, and `text` renders uncoloured — the graceful default the
    /// library already provides rather than a failure.
    pub fn editor_language(self) -> &'static str {
        match self {
            CodeTarget::Curl => "text",
            CodeTarget::JsFetch | CodeTarget::JsAxios | CodeTarget::JsXhr => "javascript",
        }
    }

    /// Position in [`CodeTarget::ALL`], for the tab strip's selected index and
    /// for element ids.
    pub fn index(self) -> usize {
        match self {
            CodeTarget::Curl => 0,
            CodeTarget::JsFetch => 1,
            CodeTarget::JsAxios => 2,
            CodeTarget::JsXhr => 3,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::CodeTarget;

    #[test]
    fn every_target_is_listed_once_and_indexed_by_its_position() {
        for (index, target) in CodeTarget::ALL.into_iter().enumerate() {
            assert_eq!(
                CodeTarget::ALL
                    .iter()
                    .filter(|other| **other == target)
                    .count(),
                1,
                "{target:?} appears more than once in CodeTarget::ALL"
            );
            assert_eq!(target.index(), index, "{target:?} is indexed wrongly");
        }
    }

    #[test]
    fn only_the_shell_target_is_unhighlighted() {
        for target in CodeTarget::ALL {
            let expected = if target == CodeTarget::Curl {
                "text"
            } else {
                "javascript"
            };
            assert_eq!(target.editor_language(), expected, "{target:?}");
        }
    }
}
