//! §21's spatial index — **a correctness precondition for painting, not an
//! optimisation.**
//!
//! The distinction is Phase 0's, and it is the reason this module exists before
//! any of the rich rendering it enables. macOS's Metal renderer stops
//! presenting the drawable past ~2.58 M path vertices in a frame and the window
//! goes **solid black**, with no panic and no log — and GPUI's content mask does
//! not save us, because its rejection happens after `paint_path` has cloned and
//! scaled the vertex buffer. 16,000 fully offscreen paths still cost 6.3 ms of
//! CPU. So a canvas without culling does not render slowly; at scale it does not
//! render at all.
//!
//! - [`grid`] — [`UniformGrid`], the hash grid itself, over `u32` keys.
//! - [`index`] — [`SpatialIndex`] and [`VisibleSet`], the typed layer that
//!   knows about nodes and edges and about *painted* bounds.
//!
//! # The measured numbers
//!
//! Measured on an **Apple M1 laptop, release profile, 2026-08-19**, with
//! `cargo run --release -p dodo-flow --example flow_scene_bench --locked`. The
//! scenes are §38's, generated by [`crate::scenes`].
//!
//! | scene | nodes / edges | build index | viewport query | visible |
//! |---|---:|---:|---:|---:|
//! | small | 100 / 200 | 0.01 ms | 1.7 µs | 34 n / 41 e |
//! | medium | 5,000 / 15,000 | 0.55 ms | 6.1 µs | 34 n / 82 e |
//! | large | 100,000 / 300,000 | 12.4 ms | 6.3 µs | 34 n / 84 e |
//! | dense | 8,000 / 16,000 | 1.03 ms | 447 µs | 2,150 n / 4,158 e |
//!
//! **The viewport query does not grow with the document.** 6.3 µs at 100,000
//! nodes against 6.1 µs at 5,000 is the claim the architecture rests on, and it
//! is a measurement rather than a complexity argument. The dense scene is
//! larger because it *finds* 6,300 elements rather than 118 — the query is
//! proportional to what it returns, which is the definition of the property
//! §16 asks for.
//!
//! # Why a uniform hash grid, benchmarked rather than assumed
//!
//! §21 names four candidates and says to start with a hash grid **and then
//! benchmark it**. The harness builds the same scene through this grid, through
//! a dense array grid over the document's bounding box, and through a brute
//! force scan, and prints all three. On the 100,000-node scene:
//!
//! | | build | viewport query | memory |
//! |---|---:|---:|---:|
//! | uniform hash grid | 12.4 ms | 6.3 µs | 13.6 MB |
//! | dense array grid | 9.7 ms | 3.9 µs | 20.5 MB |
//! | brute-force scan | — | 496 µs | 0 |
//!
//! The dense grid is genuinely faster — one multiply-add instead of a hash and
//! a chain walk — and it is **not** what ships, because it is only definable
//! over a known bounding box. An infinite canvas has none: a node dragged a
//! million units out either reallocates the whole array or falls out of the
//! index. The hash grid pays about 60 % more per query for not having that
//! failure mode, on a query that is 6 µs. That is the trade, stated as numbers
//! so the next person can retake it rather than re-derive it.
//!
//! Against the scan the answer is not close: **79× at 100,000 nodes**, and the
//! gap grows with the document because the scan is the only one of the three
//! that does.
//!
//! # Cell size
//!
//! [`index::cell_size_for`] takes twice the mean node width. The sweep behind
//! that, on the 100,000-node scene:
//!
//! | cell size | entries per node | viewport query |
//! |---:|---:|---:|
//! | 80 (0.5×) | 3.9 | 10.1 µs |
//! | 160 (1×) | 2.0 | 7.2 µs |
//! | **320 (2×)** | **1.2** | **6.3 µs** |
//! | 640 (4×) | 1.0 | 6.6 µs |
//! | 1,280 (8×) | 1.0 | 9.8 µs |
//!
//! The curve is flat-bottomed between 2× and 4× and rises at both ends, for the
//! two reasons a uniform grid always has: too fine and each item is linked into
//! many cells, too coarse and each cell returns candidates the narrow phase
//! then rejects. Twice the mean node size sits in the middle of the flat part.
//!
//! **This module names no UI framework.**

pub mod grid;
pub mod index;

pub use grid::{MAX_CELLS_PER_ITEM, UniformGrid};
pub use index::{
    DEFAULT_CELL_SIZE, SCREEN_PAINT_MARGIN_PIXELS, SpatialIndex, SyncReport, VisibleSet,
    cell_size_for, edge_painted_bounds, node_painted_bounds, query_rect,
};
