//! §21's spatial index — **a correctness precondition for painting, not an
//! optimisation.**
//!
//! The distinction is Phase 0's, and it is the reason this module exists before
//! any of the rich rendering it enables. macOS's Metal renderer stops
//! presenting the drawable past ~2.58 M path vertices in a frame and the window
//! goes **solid black**, with no panic and no log — and GPUI's content mask does
//! not save us, because its rejection happens after `paint_path` has cloned and
//! scaled the vertex buffer. 16,000 fully offscreen paths still cost 6.3 ms of
//! CPU. So a canvas without culling does not render slowly; at scale it does not
//! render at all.
//!
//! - [`grid`] — [`UniformGrid`], the hash grid itself, over `u32` keys.
//! - [`index`] — [`SpatialIndex`] and [`VisibleSet`], the typed layer that
//!   knows about nodes and edges and about *painted* bounds.
//!
//! # The measured numbers
//!
//! Measured on an **Apple M1 laptop, release profile, 2026-08-19**, in a
//! 1440×900 pane, with
//!
//! ```sh
//! cargo run --release -p dodo-flow --example flow_scene_bench --locked
//! ```
//!
//! The scenes are §38's, generated by [`crate::scenes`]. **Release only** — a
//! debug build measures the borrow checker rather than the data structure.
//!
//! | scene | nodes / edges | index build | viewport query | brute-force scan | visible |
//! |---|---:|---:|---:|---:|---:|
//! | small | 100 / 200 | 0.04 ms | 4.6 µs | 2.0 µs | 37 n / 76 e |
//! | medium | 5,000 / 15,000 | 0.76 ms | 2.3 µs | 50 µs | 36 n / 117 e |
//! | large | 100,000 / 300,000 | 14.2 ms | **2.4 µs** | 1,697 µs | 36 n / 126 e |
//! | dense | 20,000 / 40,000 | 1.84 ms | 69.7 µs | 187 µs | 1,584 n / 3,182 e |
//!
//! **The viewport query does not grow with the document.** 2.4 µs at 100,000
//! nodes and 300,000 edges against 2.3 µs at 5,000 — and against a brute-force
//! scan of the same question at 1,697 µs, which is **707× slower** and is the
//! only one of the two that grows. That flatness is the claim the architecture
//! rests on, and it is a measurement rather than a complexity argument.
//!
//! The dense scene is larger because it *finds* 4,766 elements rather than 162.
//! A query proportional to what it returns is exactly the property §16 asks
//! for.
//!
//! **The small scene is the honest exception**: at 100 nodes the scan is
//! faster than the index (2.0 µs against 4.6 µs), because 300 elements fit in
//! cache and a hash and a chain walk do not pay for themselves. The index is
//! not there for small documents, and nothing here pretends otherwise.
//!
//! # Why a uniform hash grid, benchmarked rather than assumed
//!
//! §21 names four candidates and says to start with a hash grid **and then
//! benchmark it**. The harness builds the same 100,000 node set through this
//! grid, through a dense array grid over the document's bounding box, and
//! through a brute-force scan:
//!
//! | | build | node query | memory |
//! |---|---:|---:|---:|
//! | uniform hash grid *(ships)* | 4.7 ms | 0.39 µs | 7.9 MB |
//! | dense array grid | 1.7 ms | **0.10 µs** | 1.6 MB |
//! | brute-force scan | — | 81 µs | 0 |
//!
//! The dense grid is genuinely faster — one multiply-add instead of a hash and
//! a chain walk — and it is **not** what ships, because it is only definable
//! over a known bounding box. An infinite canvas has none: a node dragged a
//! million units out either reallocates the whole array or falls out of the
//! index. The hash grid pays 4× per query for not having that failure mode, on
//! a query that is 0.39 µs and is nowhere near the frame's critical path. That
//! is the trade, stated as numbers so the next person can retake it rather than
//! re-derive it.
//!
//! Against the scan the answer is not close: **209×**, and the gap grows with
//! the document because the scan is the only one of the three that does.
//!
//! # Cell size
//!
//! [`index::cell_size_for`] takes twice the mean node extent. The sweep behind
//! that, on the 100,000-node scene (node extent 160 units):
//!
//! | cell size | entries per node | candidates | query |
//! |---:|---:|---:|---:|
//! | 80 (0.5×) | 4.60 | 43 | 0.94 µs |
//! | 160 (1×) | 3.03 | 43 | 0.48 µs |
//! | **320 (2×)** | **1.89** | **43** | **0.35 µs** |
//! | 640 (4×) | 1.41 | 67 | 0.39 µs |
//! | 1,280 (8×) | 1.20 | 84 | 0.38 µs |
//!
//! The curve is flat-bottomed from 2× outward and rises sharply below it, for
//! the two reasons a uniform grid always has: too fine and each item is linked
//! into many cells, too coarse and each cell returns candidates the narrow
//! phase then rejects. 2× is where the entry count first reaches ~1 per item
//! without the candidate set growing, which is the definition of the right cell
//! size for this structure.
//!
//! # Updating the index: what a drag costs
//!
//! One node of degree 9, in the 100,000-node / 300,000-edge scene, including
//! the route rebuilds and the spatial sync:
//!
//! | | per move |
//! |---|---:|
//! | 1,000 sub-cell moves (a real drag) | **0.50 µs** |
//! | 1,000 cell-crossing moves | 0.76 µs |
//!
//! and the number behind the gap: a sub-cell move re-linked the index **2 times
//! in 1,000**. [`SpatialIndex::update`](UniformGrid::update) compares the new
//! cell range against the old and returns without touching a chain when they
//! match, so the common case of a drag is a range comparison and nothing else.
//! Phase 3 measured the dirty propagation alone at 0.17 µs on the same machine;
//! the index adds about 0.33 µs, and nine route rebuilds are most of that.
//!
//! # The input that breaks it, measured rather than avoided
//!
//! Every number above assumes what real diagrams do: an edge joins nodes that
//! are near each other. The harness also builds the **scattered** scene —
//! 100,000 nodes whose edges connect anything to anything — and it is the one
//! result worth reading before trusting the rest:
//!
//! | | large (local edges) | scattered (document-crossing edges) |
//! |---|---:|---:|
//! | visible edges | 126 | **61,104** |
//! | viewport query | 2.4 µs | **1,721 µs** |
//! | oversized items | 0 | **276,549** |
//! | estimated vertices | 31,188 | **147,761,694** |
//! | paths dropped by the black-window guard | 0 | **60,061** |
//!
//! Nothing is wrong with the index there: an edge whose control hull spans the
//! document *is* visible from anywhere in the document, and no spatial
//! structure can cull what genuinely overlaps the viewport. It is the scene
//! that is pathological, and the failure is graceful — the guard drops paths
//! and the canvas paints incompletely rather than going black.
//!
//! **But it is a real limit and it belongs in the plan**: culling alone does
//! not bound a hairball graph, and the answer is LOD (§15) — an edge whose
//! on-screen extent is a few pixels should be a line or nothing, not a
//! tessellated Bézier. That is Phase 5 and Phase 8's, and this table is the
//! measurement that says they are required rather than nice to have.
//!
//! **This module names no UI framework.**

pub mod grid;
pub mod index;

pub use grid::{MAX_CELLS_PER_ITEM, UniformGrid};
pub use index::{
    DEFAULT_CELL_SIZE, SCREEN_PAINT_MARGIN_PIXELS, SpatialIndex, SyncReport, VisibleSet,
    cell_size_for, edge_painted_bounds, node_painted_bounds, query_rect,
};
